<#
.SYNOPSIS
    Build aarch64 Linux binary for DropWireless using Docker.
    Resolves 1Password credentials on the Windows host, then runs
    the full build inside a Docker linux/arm64 container.

.EXAMPLE
    .\build_PoC_aarch64.ps1 -Code ISM -Version 1.1.0
#>

param(
    [Parameter(Mandatory)][string]$Code,
    [Parameter(Mandatory)][string]$Version,
    [int]$VersionCheckSec = 600,
    [string]$DockerImage = "python:3.11-slim"
)

$ErrorActionPreference = "Stop"
$Code = $Code.ToUpper()

Write-Host "=== Building $Code v$Version for linux/aarch64 ===" -ForegroundColor Cyan

# --- Resolve 1Password credentials on the host ---
if (-not (Get-Command "op" -ErrorAction SilentlyContinue)) {
    Write-Error "1Password CLI 'op' not found on PATH."
    exit 1
}

Write-Host "Resolving credentials from 1Password..."
$bearer       = (op read "op://HardwareAPI/Hardware_API/API_BEARER_TOKEN" 2>$null).Trim()
$signingKey   = (op read "op://VSCode/hardware_exe/local_signing_key_hex" 2>$null).Trim()
$autonomysKey = (op read "op://DataStorage/AutoDrive/AUTONOMYS_API_KEY" 2>$null).Trim()

if ($bearer)       { Write-Host "  Bearer token: OK" }
if ($signingKey)   { Write-Host "  Signing key: OK" }
if ($autonomysKey) { Write-Host "  Autonomys API key: OK" }

# --- Verify Docker ---
if (-not (Get-Command "docker" -ErrorAction SilentlyContinue)) {
    Write-Error "Docker not found on PATH."
    exit 1
}

Write-Host "Verifying Docker ARM64 emulation..."
$archCheck = docker run --rm --platform linux/arm64 $DockerImage uname -m 2>&1
if ($archCheck -ne "aarch64") {
    Write-Error "Docker ARM64 emulation not working. Got: $archCheck"
    exit 1
}
Write-Host "  ARM64 emulation: OK" -ForegroundColor Green

# --- Run the full build inside Docker ---
$projectDir = (Get-Location).Path
# Docker on Windows needs forward-slash paths for -v bind mounts
$dockerPath = $projectDir -replace '\\','/'
if ($dockerPath -match '^([A-Za-z]):(.*)') {
    $dockerPath = '/' + $Matches[1].ToLower() + $Matches[2]
}
$svcName = "FRY_PoC_${Code}_v${Version}_linux_aarch64"
$relDir  = "release/$Version"

Write-Host "Starting Docker build..." -ForegroundColor Cyan
Write-Host "  Volume mount: ${dockerPath}:/build"

# Write the build script to a temp file so Docker can execute it from the volume
# (avoids PowerShell here-string / Windows command-line issues with bash -c)
$buildScript = Join-Path $projectDir ".docker_build.sh"
$scriptContent = @'
#!/bin/bash
set -e

echo "=== Inside Docker ($(uname -m)) ==="

# Install system deps (include build tools required to build PyInstaller on arm64)
apt-get update -qq && apt-get install -y -qq \
    binutils build-essential python3-dev libssl-dev libffi-dev zlib1g-dev pkg-config patchelf

# Install Python packages
pip install --quiet --upgrade pip
pip install --quiet pyinstaller psutil requests cryptography h3 pillow pandas pyarrow

# Metadata maps
declare -A GROUP_MAP=( [BM]=Bandwidth [IDM]=Decibel [ODM]=Decibel [ISM]=Satellite [OSM]=Satellite [RDN]=Node [SDN]=Node [SVN]=Node [AEM]=AI [IRM]=Radiation )
declare -A DISPLAY_NAME_MAP=( [BM]="Bandwidth Miner" [IDM]="Indoor Decibel Miner" [ODM]="Outdoor Decibel Miner" [ISM]="Indoor Satellite Miner" [OSM]="Outdoor Satellite Miner" [RDN]="Reward Decentralization Node" [SDN]="Storage Decentralization Node" [SVN]="Storage Validator Node" [AEM]="AI Edge Miner" [IRM]="Radiation Miner" )
declare -A METRIC_LABEL_MAP=( [BM]=Bandwidth [IDM]=Decibel [ODM]=Decibel [ISM]="GNSS stream" [OSM]="GNSS stream" [RDN]=Rewards [SDN]=Storage [SVN]=Validation [AEM]="AI inference" [IRM]=Radiation )

group=${GROUP_MAP[$CODE]:-Unknown}
display_name=${DISPLAY_NAME_MAP[$CODE]:-"$CODE Miner"}
metric_label=${METRIC_LABEL_MAP[$CODE]:-Metric}

# Generate config_profile.py
cat > config_profile.py <<PYEOF
# AUTOGENERATED. DO NOT EDIT.
MINER_CODE = "$CODE"
VERSION = "$VERSION"
GROUP = "$group"
DISPLAY_NAME = "$display_name"
METRIC_LABEL = "$metric_label"
METRIC_UNIT = ""
DEV = False
VERSION_CHECK_SEC = $VERSION_CHECK_SEC
PYEOF
echo "Generated config_profile.py"

# Find tools dir
tools_dir=""
for t in ./tools ./miner_GUI/tools; do
  [ -d "$t" ] && tools_dir=$t && break
done
if [ -z "$tools_dir" ]; then
  echo "Error: tools/ directory not found"
  exit 1
fi

# Build embedded config JSON
api_base_url="https://hardwareapi.frynetworks.com"
python3 - <<PYEOF > _tmp_config.json
import json
cfg = {
    "external_api": {"base_url": "$api_base_url", "timeout": 10.0},
    "interval_seconds": 600
}
bearer = "$BEARER_TOKEN"
if bearer:
    cfg["external_api"]["bearer_token"] = bearer
sign = "$SIGNING_KEY"
if sign:
    cfg["local_signing_key_hex"] = sign
ak = "$AUTONOMYS_API_KEY"
if ak:
    cfg.setdefault("tool_credentials", {})["autonomys_api_key"] = ak
    cfg["autonomys_upload_enabled"] = True
print(json.dumps(cfg))
PYEOF

if [ -n "$BEARER_TOKEN" ]; then
  echo "Bearer token configured"
fi

# Encrypt config
python3 "$tools_dir/make_encrypted_config.py" --in _tmp_config.json --json > enc_tmp.json
dlt=$(python3 -c "import json; print(json.load(open('enc_tmp.json'))['dlt'])")
dlp=$(python3 -c "import json; print(json.load(open('enc_tmp.json'))['dlp'])")
knt=$(python3 -c "import json; print(json.load(open('enc_tmp.json'))['knt'])")
knp=$(python3 -c "import json; print(json.load(open('enc_tmp.json'))['knp'])")

# Patch source
src_path="miner_online_simple.py"
cp "$src_path" "$src_path.bak"
line_num=$(grep -n "dlt=b''; dlp=b''; knt=b''; knp=b''" "$src_path" | cut -d: -f1)
if [ -z "$line_num" ]; then
  echo "Error: Placeholder line not found in miner_online_simple.py"
  exit 1
fi
python3 -c "
import sys
ln, dlt, dlp, knt, knp, sp = int(sys.argv[1]), sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5], sys.argv[6]
with open(sp, 'r') as f: lines = f.readlines()
lines[ln-1] = f'    dlt = {dlt}\n'
lines.insert(ln, f'    dlp = {dlp}\n')
lines.insert(ln+1, f'    knt = {knt}\n')
lines.insert(ln+2, f'    knp = {knp}\n')
with open(sp, 'w') as f: f.writelines(lines)
" $line_num "$dlt" "$dlp" "$knt" "$knp" "$src_path"

# PyInstaller build
svc_dist_dir="dist/svc/$CODE"
mkdir -p "$svc_dist_dir"

# Build extra --add-data flags based on miner code
extra_data=()
if [ "$CODE" = "RDN" ] && [ -d "docker/diiisco" ]; then
  extra_data+=(--add-data "docker/diiisco:docker/diiisco")
  echo "Bundling DIIISCO Docker Compose stack"
fi

python3 -m PyInstaller \
  --clean --onefile --noconsole --noconfirm \
  --name "$SVC_NAME" \
  --distpath "$svc_dist_dir" \
  --collect-all pyarrow \
  --exclude-module PySide6 --exclude-module matplotlib \
  --exclude-module numpy --exclude-module sounddevice \
  --exclude-module portaudio --exclude-module pyside6 \
  --exclude-module numba \
  --exclude-module pyarrow.tests \
  "${extra_data[@]}" \
  miner_online_simple.py

# Move to release
out="release/$VERSION"
mkdir -p "$out"
mv "$svc_dist_dir/$SVC_NAME" "$out/$SVC_NAME"

# SHA256
(cd "$out" && sha256sum "$SVC_NAME" > "$SVC_NAME.sha256")

# Restore source
mv "$src_path.bak" "$src_path"
rm -f _tmp_config.json enc_tmp.json

echo ""
echo "=== Build complete: $out/$SVC_NAME ==="
echo "=== SHA256: $out/$SVC_NAME.sha256 ==="
'@
# Write with Unix line endings (LF) so bash can execute it
[System.IO.File]::WriteAllText($buildScript, $scriptContent.Replace("`r`n", "`n"))

docker run --rm --platform linux/arm64 `
    -v "${dockerPath}:/build" `
    -w /build `
    -e "DEBIAN_FRONTEND=noninteractive" `
    -e "CODE=$Code" `
    -e "VERSION=$Version" `
    -e "VERSION_CHECK_SEC=$VersionCheckSec" `
    -e "SVC_NAME=$svcName" `
    -e "BEARER_TOKEN=$bearer" `
    -e "SIGNING_KEY=$signingKey" `
    -e "AUTONOMYS_API_KEY=$autonomysKey" `
    $DockerImage bash /build/.docker_build.sh

# Clean up temp build script
Remove-Item -Path $buildScript -ErrorAction SilentlyContinue

if ($LASTEXITCODE -ne 0) {
    Write-Error "Docker build failed with exit code $LASTEXITCODE"
    exit $LASTEXITCODE
}

$outputPath = Join-Path $projectDir "release\$Version\$svcName"
$sha256Path = "${outputPath}.sha256"

if (Test-Path $outputPath) {
    Write-Host ""
    Write-Host "Build successful!" -ForegroundColor Green
    Write-Host "  Binary:  release\$Version\$svcName"
    Write-Host "  SHA256:  release\$Version\$svcName.sha256"
    Write-Host ""
    Write-Host "Copy these to the drop/ directory for DropWireless delivery." -ForegroundColor Yellow
} else {
    Write-Error "Build output not found at $outputPath"
    exit 1
}
