# AUTOGENERATED. DO NOT EDIT.
MINER_CODE = "BM"
VERSION = "1.8.2"
GROUP = "Bandwidth"
DISPLAY_NAME = "Bandwidth Miner"
METRIC_LABEL = "Bandwidth"
METRIC_UNIT = ""
DEV = False
VERSION_CHECK_SEC = 600
GEOIP_SHARED_SUBPATH = "FryNetworks/GeoLite2/GeoLite2-Country.mmdb"

