# AUTOGENERATED. DO NOT EDIT.
MINER_CODE = "SVN"
VERSION = "1.0.0"
GROUP = "Node"
DISPLAY_NAME = "Storage Validator Node"
METRIC_LABEL = "Validation"
METRIC_UNIT = ""
DEV = False
VERSION_CHECK_SEC = 600
GEOIP_SHARED_SUBPATH = "FryNetworks/GeoLite2/GeoLite2-Country.mmdb"

