# AUTOGENERATED. DO NOT EDIT.
MINER_CODE = "RDN"
VERSION = "1.9.12"
GROUP = "Node"
DISPLAY_NAME = "Reward Decentralization Node"
METRIC_LABEL = "Rewards"
METRIC_UNIT = ""
DEV = False
VERSION_CHECK_SEC = 600
GEOIP_SHARED_SUBPATH = "FryNetworks/GeoLite2/GeoLite2-Country.mmdb"

